# Generated by Django 2.0.5 on 2018-05-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hp', models.IntegerField()),
                ('mele', models.IntegerField()),
                ('magic', models.IntegerField()),
                ('lvl', models.IntegerField()),
                ('earth', models.IntegerField()),
                ('wind', models.IntegerField()),
                ('wather', models.IntegerField()),
                ('fire', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_character', models.CharField(max_length=100)),
                ('mele', models.IntegerField()),
                ('magic', models.IntegerField()),
                ('earth', models.IntegerField()),
                ('wind', models.IntegerField()),
                ('wather', models.IntegerField()),
                ('fire', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('mn', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lvl', models.IntegerField()),
                ('mele', models.IntegerField()),
                ('magic', models.IntegerField()),
                ('earth', models.IntegerField()),
                ('wind', models.IntegerField()),
                ('wather', models.IntegerField()),
                ('fire', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
