# Generated by Django 2.0.5 on 2018-05-16 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_auto_20180515_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='hp',
            new_name='hp_act',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='mn',
            new_name='mn_act',
        ),
        migrations.AddField(
            model_name='profile',
            name='hp_tot',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='mn_tot',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
