# Generated by Django 2.0.5 on 2018-05-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0005_auto_20180516_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skin',
        ),
        migrations.AddField(
            model_name='character',
            name='skin',
            field=models.ImageField(blank=True, null=True, upload_to='skin_img'),
        ),
    ]
