# Generated by Django 2.0.5 on 2018-05-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0006_auto_20180516_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='boss',
            field=models.ManyToManyField(blank=True, default=1, null=True, to='points.Boss'),
        ),
    ]
