# Generated by Django 2.0.5 on 2018-05-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0007_auto_20180516_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='boss',
            field=models.ManyToManyField(blank=True, null=True, to='points.Boss'),
        ),
    ]
