# Generated by Django 2.0.5 on 2018-05-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0008_auto_20180516_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='details',
            field=models.TextField(default='lorem'),
        ),
    ]
