# Generated by Django 2.0.5 on 2018-05-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0010_auto_20180517_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skin',
        ),
        migrations.AlterField(
            model_name='profile',
            name='exp',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lvl',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
