# Generated by Django 2.0.5 on 2018-05-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0013_item_skin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monsters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('skin', models.ImageField(blank=True, null=True, upload_to='skin_img')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='first_time',
            field=models.BooleanField(default=True),
        ),
    ]
