# Generated by Django 2.0.5 on 2018-05-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0014_auto_20180519_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='boss',
            name='skin',
            field=models.ImageField(blank=True, null=True, upload_to='skin_img'),
        ),
    ]
