# Generated by Django 2.0.5 on 2018-05-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0016_auto_20180519_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='monsters',
            name='hp_act',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='monsters',
            name='hp_tot',
            field=models.IntegerField(default=15),
        ),
    ]
